### ISSUE TITLE
Дз 1

### ISSUE THREAD

**Issue by Vantwozz** [Demezy/todo_app#2]
У тебя не работает ссылка на apk, обнови как можно скорее, пожалуйста.

**Comment by Demezy** [comment]
проверил, загрушается https://github.com/Demezy/todo_app/releases/download/untagged-3ce9b9b2c5f4b54647ff/app-release.apk

**Comment by Demezy** [comment]
случайно закрыл

**Comment by ChaserVasya** [comment]
нет ссылки на апк
